version: '3.7'

services:
  pdb:
    image: postgres:latest
    container_name: pdb
    restart: unless-stopped
    volumes:
      - ./src/db/init-db-scripts:/docker-entrypoint-initdb.d
      - ./tmp/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_INIT=${DB_APP_USER}:${DB_APP_PASSWORD}:${DB_APP_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 20
    ports:
      - '5432:5432'
    networks:
      - intranet

  migrate:
    image: migrate/migrate:latest
    profiles:
      - tools
    volumes:
      - ./src/db/migrations:/migrations
    command:
      - "-database"
      - "${DB_URI_MIGRATIONS}"
      - "-path"
      - "/migrations/"
      - "up"
    depends_on:
      pdb:
        condition: service_healthy
    networks:
      - intranet

networks:
  intranet:


